# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './detectphone.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1061, 592)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lblStatus = QtWidgets.QLabel(Frame)
        self.lblStatus.setText("")
        self.lblStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout.addWidget(self.lblStatus)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButtonTest = QtWidgets.QPushButton(Frame)
        self.pushButtonTest.setObjectName("pushButtonTest")
        self.verticalLayout.addWidget(self.pushButtonTest)
        self.pbSaveCorrect = QtWidgets.QPushButton(Frame)
        self.pbSaveCorrect.setObjectName("pbSaveCorrect")
        self.verticalLayout.addWidget(self.pbSaveCorrect)
        self.pbSaveWrong = QtWidgets.QPushButton(Frame)
        self.pbSaveWrong.setObjectName("pbSaveWrong")
        self.verticalLayout.addWidget(self.pbSaveWrong)
        self.pushButtonExit = QtWidgets.QPushButton(Frame)
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.verticalLayout.addWidget(self.pushButtonExit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.labelImage = QtWidgets.QLabel(Frame)
        self.labelImage.setMinimumSize(QtCore.QSize(1024, 756))
        self.labelImage.setMaximumSize(QtCore.QSize(1024, 756))
        self.labelImage.setText("")
        self.labelImage.setObjectName("labelImage")
        self.horizontalLayout.addWidget(self.labelImage)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 9)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Detect Tools"))
        self.label.setText(_translate("Frame", "DetectPhone"))
        self.label_2.setText(_translate("Frame", "Status:"))
        self.pushButtonTest.setText(_translate("Frame", "Test"))
        self.pbSaveCorrect.setText(_translate("Frame", "Save(C)"))
        self.pbSaveWrong.setText(_translate("Frame", "Save(W)"))
        self.pushButtonExit.setText(_translate("Frame", "Done"))
